version: 2
jobs:
  build:
    docker:
      - image: microsoft/dotnet
    steps:
      - checkout
      - run:
          name: Greeting
          command: echo Hello, world.
      - run:
          name: Print the Current Time
          command: date
      - run:
          name: dotnet core run project
          command: dotnet run --project ./src/hello-world-netcore/ CircleCI
      - run:
          name: dotnet standard run project
          command: dotnet build ./src/hello-world-netstandard/
      - run:
          name: dotnet standard run project
          command: dotnet test test/hello-world-netstandard.UnitTest/