version: 2
jobs:
  build:
    docker:
      - image: microsoft/dotnet
    steps:
      - checkout
      - run:
          name: Greeting
          command: echo Hello, world.
      - run:
          name: Print the Current Time
          command: date
      - run:
          name: dotnet core run project
          command: dotnet run --project ./src/hello-world-netcore/ CircleCI
      - run:
          name: dotnet standard project build
          command: dotnet build ./src/hello-world-netstandard/
      - run:
          name: trying sudo
          command: apt-get install -y sudo
      - run:
          name: dotnet standard project test
          command:sudo dotnet test test/hello-world-netstandard.UnitTest/
      - run:
          name: dotnet standard project build
          command: dotnet build ./src/xpdfexecutor/
      - run:
          name: dotnet standard project test
          command: strace -f -t -e trace=process dotnet test test/xpdfexecutor.UnitTest/
      - run:
          name: Set permissions
          command: chmod -R 777 .
      - run:
          name: list folder contents
          command: ls -a test/xpdfexecutor.UnitTest/bin/Debug/netcoreapp2.1/