version: 2.1
jobs:
  build:
    docker:
        - image: microsoft/dotnet
    environment:
      ENV: CI
      TEST_REPORTS: /tmp/test-reports

    branches:
      only:
        - master

    steps:
      - checkout

      - run:
          name: Print date
          command: echo date

      - run:
          name: Building source code
          command: |
          echo date
          echo time
          mkdir -p /tmp/
          ls -alFR
          echo Hello, world!
          echo dotnet core run './src/hello-world-netcore/' project
          dotnet run --project ./src/hello-world-netcore/ CircleCI
          echo dotnet standard './src/hello-world-netstandard/' project build
          dotnet build ./src/hello-world-netstandard/
          echo dotnet standard './src/xpdfexecutor/' project build
          dotnet build ./src/xpdfexecutor/
          echo dotnet standard './src/UsingEPPlus/' project build
          dotnet build ./src/UsingEPPlus/

      - run:
          name: Executing tests
          command: |
          mkdir -p ${TEST_REPORTS}
          echo dotnet standard './test/hello-world-netstandard.UnitTest/' project test
          dotnet test ./test/hello-world-netstandard.UnitTest/
          echo dotnet standard './test/xpdfexecutor.UnitTest/' project test
          dotnet test ./test/xpdfexecutor.UnitTest/
          echo dotnet standard './test/UsingEPPlus.UnitTest/' project test
          dotnet test ./test/UsingEPPlus.UnitTest/