version: 2
jobs:
  build:
    docker:
      - image: microsoft/dotnet
    steps:
      - checkout
      - run:
          name: Greeting
          command: echo Hello, world.
      - run:
          name: Print the Current Time
          command: date
      - run:
          name: Show folder content
          command: ls -alFR
      - run:
          name: dotnet core run project
          command: dotnet run --project ./src/hello-world-netcore/ CircleCI
      - run:
          name: dotnet standard project build
          command: dotnet build ./src/hello-world-netstandard/
      - run:
          name: dotnet standard project test
          command: dotnet test test/hello-world-netstandard.UnitTest/
      - run:
          name: dotnet standard project build
          command: dotnet build ./src/xpdfexecutor/
      - run:
          name: dotnet standard project test
          command: dotnet test test/xpdfexecutor.UnitTest/
      - run:
          name: dotnet standard project build
          command: dotnet build ./src/UsingEPPlus/
      - run:
          name: dotnet standard project test
          command: dotnet test test/UsingEPPlus.UnitTest/